language: go
go:
  - 1.14.x
  - 1.15.x
  - master

services:
  - mysql

env:
  - GO111MODULE=on

before_install:
  - openssl aes-256-cbc -K $encrypted_da6bace51577_key -iv $encrypted_da6bace51577_iv -in lottery_conf.yaml.enc -out lottery_conf.yaml -d
  - go mod download
  - mysql -e 'CREATE DATABASE lottery_test;'
  - wget https://downloads.apache.org/kafka/2.7.0/kafka_2.13-2.7.0.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 5
  - kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --topic WinningTopic --partitions 1 --replication-factor 1

script:
  - mv lottery_conf.yaml ~/lottery_conf.yaml
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go build cmd/auth/main.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
