// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.0
// source: proto/lottery_info.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LotteryRatesValue int32

const (
	LotteryRates_LOW_VAL  LotteryRatesValue = 0
	LotteryRates_HIGH_VAL LotteryRatesValue = 1
)

// Enum value maps for LotteryRatesValue.
var (
	LotteryRatesValue_name = map[int32]string{
		0: "LOW_VAL",
		1: "HIGH_VAL",
	}
	LotteryRatesValue_value = map[string]int32{
		"LOW_VAL":  0,
		"HIGH_VAL": 1,
	}
)

func (x LotteryRatesValue) Enum() *LotteryRatesValue {
	p := new(LotteryRatesValue)
	*p = x
	return p
}

func (x LotteryRatesValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LotteryRatesValue) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lottery_info_proto_enumTypes[0].Descriptor()
}

func (LotteryRatesValue) Type() protoreflect.EnumType {
	return &file_proto_lottery_info_proto_enumTypes[0]
}

func (x LotteryRatesValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LotteryRatesValue.Descriptor instead.
func (LotteryRatesValue) EnumDescriptor() ([]byte, []int) {
	return file_proto_lottery_info_proto_rawDescGZIP(), []int{0, 0}
}

type LotteryRates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Rates []*LotteryRates_AwardRate `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
}

func (x *LotteryRates) Reset() {
	*x = LotteryRates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lottery_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryRates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryRates) ProtoMessage() {}

func (x *LotteryRates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lottery_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryRates.ProtoReflect.Descriptor instead.
func (*LotteryRates) Descriptor() ([]byte, []int) {
	return file_proto_lottery_info_proto_rawDescGZIP(), []int{0}
}

func (x *LotteryRates) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LotteryRates) GetRates() []*LotteryRates_AwardRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type LotteryDuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *LotteryDuration) Reset() {
	*x = LotteryDuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lottery_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryDuration) ProtoMessage() {}

func (x *LotteryDuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lottery_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryDuration.ProtoReflect.Descriptor instead.
func (*LotteryDuration) Descriptor() ([]byte, []int) {
	return file_proto_lottery_info_proto_rawDescGZIP(), []int{1}
}

func (x *LotteryDuration) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *LotteryDuration) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type WinningInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Lottery uint64 `protobuf:"varint,2,opt,name=lottery,proto3" json:"lottery,omitempty"`
	Award   uint64 `protobuf:"varint,3,opt,name=award,proto3" json:"award,omitempty"`
}

func (x *WinningInfo) Reset() {
	*x = WinningInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lottery_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WinningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinningInfo) ProtoMessage() {}

func (x *WinningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lottery_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinningInfo.ProtoReflect.Descriptor instead.
func (*WinningInfo) Descriptor() ([]byte, []int) {
	return file_proto_lottery_info_proto_rawDescGZIP(), []int{2}
}

func (x *WinningInfo) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *WinningInfo) GetLottery() uint64 {
	if x != nil {
		return x.Lottery
	}
	return 0
}

func (x *WinningInfo) GetAward() uint64 {
	if x != nil {
		return x.Award
	}
	return 0
}

type LotteryRates_AwardRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rate  uint32            `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Value LotteryRatesValue `protobuf:"varint,3,opt,name=value,proto3,enum=lottery.LotteryRatesValue" json:"value,omitempty"`
}

func (x *LotteryRates_AwardRate) Reset() {
	*x = LotteryRates_AwardRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lottery_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotteryRates_AwardRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryRates_AwardRate) ProtoMessage() {}

func (x *LotteryRates_AwardRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lottery_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryRates_AwardRate.ProtoReflect.Descriptor instead.
func (*LotteryRates_AwardRate) Descriptor() ([]byte, []int) {
	return file_proto_lottery_info_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LotteryRates_AwardRate) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LotteryRates_AwardRate) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *LotteryRates_AwardRate) GetValue() LotteryRatesValue {
	if x != nil {
		return x.Value
	}
	return LotteryRates_LOW_VAL
}

var File_proto_lottery_info_proto protoreflect.FileDescriptor

var file_proto_lottery_info_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x35, 0x0a, 0x05, 0x72,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x61, 0x74, 0x65,
	0x73, 0x2e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x52, 0x61, 0x74, 0x65, 0x52, 0x05, 0x72, 0x61, 0x74,
	0x65, 0x73, 0x1a, 0x62, 0x0a, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x52, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x4c, 0x4f, 0x57, 0x5f, 0x56, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x48, 0x49, 0x47, 0x48, 0x5f, 0x56, 0x41, 0x4c, 0x10, 0x01, 0x22, 0x71, 0x0a, 0x0f, 0x4c, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x2c, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x51, 0x0a,
	0x0b, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x77,
	0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x77, 0x61, 0x72, 0x64,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_lottery_info_proto_rawDescOnce sync.Once
	file_proto_lottery_info_proto_rawDescData = file_proto_lottery_info_proto_rawDesc
)

func file_proto_lottery_info_proto_rawDescGZIP() []byte {
	file_proto_lottery_info_proto_rawDescOnce.Do(func() {
		file_proto_lottery_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lottery_info_proto_rawDescData)
	})
	return file_proto_lottery_info_proto_rawDescData
}

var file_proto_lottery_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_lottery_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_lottery_info_proto_goTypes = []interface{}{
	(LotteryRatesValue)(0),         // 0: lottery.LotteryRates.value
	(*LotteryRates)(nil),           // 1: lottery.LotteryRates
	(*LotteryDuration)(nil),        // 2: lottery.LotteryDuration
	(*WinningInfo)(nil),            // 3: lottery.WinningInfo
	(*LotteryRates_AwardRate)(nil), // 4: lottery.LotteryRates.AwardRate
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_proto_lottery_info_proto_depIdxs = []int32{
	4, // 0: lottery.LotteryRates.rates:type_name -> lottery.LotteryRates.AwardRate
	5, // 1: lottery.LotteryDuration.start:type_name -> google.protobuf.Timestamp
	5, // 2: lottery.LotteryDuration.end:type_name -> google.protobuf.Timestamp
	0, // 3: lottery.LotteryRates.AwardRate.value:type_name -> lottery.LotteryRates.value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_lottery_info_proto_init() }
func file_proto_lottery_info_proto_init() {
	if File_proto_lottery_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lottery_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryRates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lottery_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryDuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lottery_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WinningInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lottery_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotteryRates_AwardRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lottery_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lottery_info_proto_goTypes,
		DependencyIndexes: file_proto_lottery_info_proto_depIdxs,
		EnumInfos:         file_proto_lottery_info_proto_enumTypes,
		MessageInfos:      file_proto_lottery_info_proto_msgTypes,
	}.Build()
	File_proto_lottery_info_proto = out.File
	file_proto_lottery_info_proto_rawDesc = nil
	file_proto_lottery_info_proto_goTypes = nil
	file_proto_lottery_info_proto_depIdxs = nil
}
